apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      name: postgres
  externalIPs:
    - "169.57.42.179"
  selector:
    app: postgres

