apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: kubeflow
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      name: minio
  externalIPs:
    - "172.18.0.2"
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-ui
  namespace: kubeflow
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      name: ml-pipeline-ui
  externalIPs:
    - "172.18.0.2"
  selector:
    app: ml-pipeline-ui


