kind: PersistentVolume
apiVersion: v1
metadata:
  name: elyra-pv-volume
  labels:
    type: local
    app: elyra
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/jovyan/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elyra-pv-claim
  labels:
    app: elyra
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
