---
apiVersion: v1
kind: Service
metadata:
  name: elyra
  namespace: default
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      name: elyra
  externalIPs:
    - "169.50.31.58"
  selector:
    app: elyra

