kind: PersistentVolume
apiVersion: v1
metadata:
  name: nifi-pv-volume
  labels:
    type: local
    app: nifi
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nifi-pv-claim
  labels:
    app: nifi
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
