apiVersion: v1
kind: Service
metadata:
  name: nifi
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: nifi
  externalIPs:
    - "169.57.42.179"
  selector:
    app: nifi

