apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: iot
spec:
  ports:
    - port: 1883
      protocol: TCP
      targetPort: 1883
      name: mqtt
  externalIPs:
    - "158.177.161.40"
  selector:
    app: mqtt

