apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: grafana
  externalIPs:
    - "169.57.42.179"
  selector:
    app: grafana

