apiVersion: v1
kind: Pod
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  containers:
  - name: pgadmin
    image: dpage/pgadmin4:latest
    env:
    - name: PGADMIN_DEFAULT_EMAIL
      value: "user@domain.com"
    - name: PGADMIN_DEFAULT_PASSWORD
      value: "SuperSecret5432"
    ports:
    - containerPort: 80
        
