apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: pgadmin
  externalIPs:
    - "169.57.42.179"
  selector:
    app: pgadmin

