---
apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: default
spec:
  ports:
    - port: 1880
      protocol: TCP
      targetPort: 1880
      name: nodered
  externalIPs:
    - "159.122.187.212"
  selector:
    app: nodered
---
apiVersion: v1
kind: Service
metadata:
  name: nodered-ui
  namespace: default
spec:
  ports:
    - port: 1880
      protocol: TCP
      targetPort: 1880
      name: nodered-ui
  selector:
    app: nodered
