apiVersion: v1
kind: Service
metadata:
  name: mosquitto-0
  namespace: default
spec:
  ports:
    - port: 1883
      protocol: TCP
      targetPort: 1883
      name: mosquitto-0
  externalIPs:
    - "169.57.42.179"
  selector:
    app: mosquitto-0

